### ISSUE TITLE
Como adicionar uma lista de imagens para anotação?

### ISSUE THREAD

**Issue by HyanBatista** [lucaslioli/ocranno#25]
Estou tentando usar a ferramenta para fazer anotações, mas não há um lugar claro na interface para adicionar os arquivos. Eu precisaria adicionar manualmente no banco de dados? Se sim, qual o formato que devo usar?

**Comment by lucaslioli** [comment]
Olá Hyan.
Os arquivos são informado no cadastro das próprias páginas, utilizando seus respectivos caminhos -- conforme mostra o [modelo](https://github.com/lucaslioli/ocranno/blob/master/documentation/db-model.png), na tabela pages, coluna file_name.
Inicialmente o sistema foi criado para utilizar PDFs, mas poderia ser facilmente adaptado para mostrar imagens conforme o tipo do arquivo no caminho cadastrado.
